name: 3dgs-mcmc
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - cudatoolkit=11.7
  - plyfile
  - pytorch=1.13.1
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - tqdm
  - pip
  - pip:
    - -r requirements.txt
    - ./submodules/diff-gaussian-rasterization
    - ./submodules/simple-knn
